yarnPath: .yarn/releases/yarn-3.2.0.cjs
enableScripts: false
enableTelemetry: false
nodeLinker: node-modules
enableStrictSsl: false

#networkSettings:
#  "*.voximplant.internal":
#    enableNetwork: true
#npmRegistryServer: "https://npm.voximplant.internal"

enableNetwork: true
